Problem definition and test data
ArsenyVelichko/Intelligent-Placer pull request #1
Opened 2022-02-19 19:37 UTC by ArsenyVelichko

2022-02-22 19:17 UTC, sqrtyyy requested changes

2022-02-22 19:17 UTC, sqrtyyy commented on README.md
> ++ При перекрытие объектов друг другом обусловимся, что площадь перекрытия не должна превышать ```5-10%``` от площади всего объекта.
```suggestion
+ При перекрытии объектов друг другом обусловимся, что площадь перекрытия не должна превышать ```5-10%``` от площади всего объекта.
```

2022-02-26 18:27 UTC, ArsenyVelichko commented on README.md
> ++ При перекрытие объектов друг другом обусловимся, что площадь перекрытия не должна превышать ```5-10%``` от площади всего объекта.
Поправил

2022-02-26 19:31 UTC, FaceHunterr commented on README.md
> ++ Не должно присутсвовать объектов лишь частично расположенных в кадре.
Небольшая опечатка в слове "присутствовать"

2022-02-26 19:38 UTC, FaceHunterr commented
Вроде бы всё нормально. Только вопрос есть: на некоторых изображениях присутствуют тени предметов, занимающие достаточно большую площадь относительно площади самого предмета (к примеру, у скотча). Не будут ли эти тени сильно мешать?

2022-02-26 20:35 UTC, sqrtyyy approved these changes

2022-03-22 11:13 UTC, merged